{
 "title": "Puppet Server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "puppetserver",
    "label": "Puppet server",
    "query": "label_values(puppetserver_compiler_seconds,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "JRuby Usage",
   "type": "graph",
   "description": "* `num jrubies`: number of JRuby instances (constant)\n* `num free jrubies`: number of JRuby instances free\n* `average free jrubies`: average free JRubies over time\n* `average requested jrubies`: average requested JRubies over time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetserver_jruby_requested_jrubies_histo{instance=~\"$puppetserver\", measurement=\"Mean\"}",
     "legendFormat": "average requested jrubies"
    },
    {
     "expr": "puppetserver_jruby_free_jrubies_histo{instance=~\"$puppetserver\", measurement=\"Mean\"}",
     "legendFormat": "average free jrubies"
    },
    {
     "expr": "puppetserver_jruby_num_free_jrubies{instance=~\"$puppetserver\"}",
     "legendFormat": "num free jrubies"
    },
    {
     "expr": "puppetserver_jruby_num_jrubies{instance=~\"$puppetserver\"}",
     "legendFormat": "num jrubies"
    }
   ]
  },
  {
   "title": "JRuby Pool Timers",
   "type": "graph",
   "description": "* `borrow time`: average time a JRuby is borrowed for\n* `wait time`: average time Puppet Server spends waiting to borrow a JRuby to service a request\n* `lock held time`: average time the lock on the JRuby pool is held\n* `lock wait time`: average time Puppet Server spends waiting to acquire the lock\n* `jrubies free time`: This metric’s average value should greater than 1; if it isn’t, more JRubies or another compile master might be needed to keep up with requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "puppetserver_jruby_lock_wait_timer{instance=~\"$puppetserver\",measurement=\"Mean\"}",
     "legendFormat": "lock wait time"
    },
    {
     "expr": "puppetserver_jruby_lock_held_timer{instance=~\"$puppetserver\",measurement=\"Mean\"}",
     "legendFormat": "lock held time"
    },
    {
     "expr": "puppetserver_jruby_wait_timer{instance=~\"$puppetserver\",measurement=\"Mean\"}",
     "legendFormat": "wait timer"
    },
    {
     "expr": "puppetserver_jruby_borrow_timer{instance=~\"$puppetserver\",measurement=\"Mean\"}",
     "legendFormat": "borrow timer"
    },
    {
     "expr": "puppetserver_jruby_free_jrubies_histo{instance=~\"$puppetserver\",measurement=\"Mean\"}",
     "legendFormat": "jrubies free time"
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "graph",
   "description": "Heap and non-heap memory used, number of cpus available.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "puppetserver_memory_bytes_used{instance=~\"$puppetserver\",area=\"heap\"}",
     "legendFormat": "heap used"
    },
    {
     "expr": "puppetserver_memory_bytes_used{instance=~\"$puppetserver\",area=\"non-heap\"}",
     "legendFormat": "non-heap used"
    }
   ]
  },
  {
   "title": "Request Durations",
   "type": "graph",
   "description": "Average request time by type - time the server spends serving each type of request, including time waiting to acquire a JRuby",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "puppetserver_http_requests_duration_seconds{instance=~\"$puppetserver\",endpoint=\"total\",measurement=\"Mean\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Compilation",
   "type": "graph",
   "description": "Time spent in different parts of handling a Catalog request\n\n* `compile`: time to compile catalogs.\n* `static_compile`: time to do a static compile of catalogs.\n* `static compile postprocessing`: time to do postprocessing of static catalog, including inlining file metadata.\n* `function calls`: time spent calling functions (included in `compile` time)\n* `find_node`: time to get node object (not included in `compile` time)\n* `find_facts`: time to parse facts sent as part of catalog request (not included in `compile` time)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "puppetserver_compiler_seconds{instance=~\"$puppetserver\",function=\"compile\",measurement=\"Mean\"} ",
     "legendFormat": "Dynamic catalog compile"
    },
    {
     "expr": "puppetserver_compiler_seconds{instance=~\"$puppetserver\",function=\"find_node\",measurement=\"Mean\"} ",
     "legendFormat": "Find node"
    },
    {
     "expr": "puppetserver_compiler_seconds{instance=~\"$puppetserver\",function=\"find_facts\",measurement=\"Mean\"}",
     "legendFormat": "Find facts"
    },
    {
     "expr": "puppetserver_compiler_seconds_sum{measurement=\"Mean\"} * 1000",
     "legendFormat": "Full catalog compile"
    }
   ]
  },
  {
   "title": "External HTTP Communications",
   "type": "graph",
   "description": "Time to make HTTP requests to other services\n\n* `PuppetDB: replace facts`: time to send a \"facts replace\" command to PuppetDB (part of a catalog compile)\n* `PuppetDB: replace catalog`: time to send a \"catalog replace\" command to PuppetDB (part of a catalog compile)\n* `PuppetDB: store report`: time to send a \"report store\" command to PuppetDB (part of handling a report request)\n* `PuppetDB: find facts`: time to get facts from PuppetDB (part of a node and catalog request, if the facts for the node are not cached)\n* `PuppetDB: search resources`: time to get exported resources from PuppetDB (part of a catalog compile if exported resources are used)\n*`PuppetDB: query`: time to execute a PuppetDB query (part of a catalog compile if the puppetdb query function is used)\n* `Http report processor`: time to submit a report to the http report url (if the http report processor is used)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetdb_duration_seconds{instance=~\"$puppetserver\",function=\"command.replace_facts\",measurement=\"Mean\"} ",
     "legendFormat": "PuppetDB: replace fasts"
    },
    {
     "expr": "puppetserver_puppetdb_duration_seconds{instance=~\"$puppetserver\",function=\"command.replace_catalog\",measurement=\"Mean\"}",
     "legendFormat": "PuppetDB: replace catalog"
    },
    {
     "expr": "puppetserver_puppetdb_duration_seconds{instance=~\"$puppetserver\",function=\"command.store_report\",measurement=\"Mean\"}",
     "legendFormat": "PuppetDB: store report"
    },
    {
     "expr": "puppetserver_puppetdb_duration_seconds{instance=~\"$puppetserver\",function=\"facts.find\",measurement=\"Mean\"}",
     "legendFormat": "PuppetDB: find facts"
    },
    {
     "expr": "puppetserver_puppetdb_duration_seconds{instance=~\"$puppetserver\",function=\"resource.search\",measurement=\"Mean\"}",
     "legendFormat": "PuppetDB:  search resources"
    }
   ]
  },
  {
   "title": "Request Ratios - old",
   "type": "graph",
   "description": "Percentage of requests handled of each type.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Percentage of Requests" }
   ],
   "targets": [
    {
     "target": "alias(scale(puppetlabs.puppet5.http.puppet-v3-catalog-___-percentage, 100), 'catalog')"
    },
    {
     "target": "alias(scale(puppetlabs.puppet5.http.puppet-v3-report-___-percentage, 100), 'report')"
    },
    {
     "target": "alias(scale(puppetlabs.puppet5.http.puppet-v3-node-___-percentage, 100), 'node')"
    },
    {
     "target": "alias(scale(puppetlabs.puppet5.http.puppet-v3-file_metadatas-___-percentage, 100), 'file_metadatas')"
    },
    {
     "target": "alias(scale(puppetlabs.puppet5.http.puppet-v3-file_metadata-___-percentage, 100), 'file_metadata')"
    },
    {
     "target": "alias(scale(puppetlabs.puppet5.http.puppet-v3-file_content-___-percentage, 100), 'file_content')"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "description": "Number of active requests and average number of active requests (over ~ 5 minutes).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetserver_http_requests_active{instance=~\"$puppetserver\"}",
     "legendFormat": "Currently active requests"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$puppetserver\",mode=\"user\"}[$__interval])) by (mode) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$puppetserver\",mode=\"system\"}[$__interval])) by (mode) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$puppetserver\",mode=\"softirq\"}[$__interval])) by (mode) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load average (5m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$puppetserver\"}",
     "legendFormat": "Load 1min"
    }
   ]
  },
  {
   "title": "Context / Interrupts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=~\"$puppetserver\"}[$__interval])",
     "legendFormat": "Context switch"
    },
    {
     "expr": "rate(node_intr_total{instance=~\"$puppetserver\"}[$__interval])",
     "legendFormat": "Interrupts"
    }
   ]
  }
 ]
}